- hosts: localhost
  gather_facts: true
  vars:
    brew_cask_packages:
      - docker
      - google-chrome
      - google-drive
      - slack
      - spotify
      - alacritty
    brew_packages:
      - docker-compose
      - docker
      - git
      - go
      - nmap
      - openssl
      - packer
      - tmux
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
  tasks:
    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
